name: Run The Test

on: [push]

jobs:
  test_determining_lowest_number:
    name: Test find_lowest_number.py
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Run Test 1 Check The Lowest Number From 10 Numbers
        run: |
          python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
          diff test_data/test1_output.txt test_data/test1_expected.txt

      - name: Run Test 2 Check The Result When There Is A Single Number
        run: |
          python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
          diff test_data/test2_output.txt test_data/test2_expected.txt

      - name: Run Test 3 Check for a Blank File
        run: |
          python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
          diff test_data/test3_output.txt test_data/test3_expected.txt
